import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [Component, setComponent] = useState(null);
  useEffect(() => {
    if (typeof window !== 'undefined') {
      setComponent(React.lazy(() => import('host/Hello')));
    }
  }, []);

  return (
    <>
      <Head>
        <title>Calc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
          <h1>Calc</h1>
          {Component && <Component />}
        </main>
      </div>
    </>
  );
}
